#!/usr/bin/env python3
"""
CB Technical Documentation Generator

This script generates technical documentation for a module using the index file as a checklist.
It is designed to be run by AI worker agents (Claude) to ensure complete documentation coverage.

IMPORTANT: This script is meant to be invoked by Claude Code agents.
The actual documentation content is generated by the AI, not by this script.
This script provides the structure and saves the AI-generated content.

Usage:
    python generate_documentation.py --module <alias> [--full|--delta]

Modes:
    --full      Document all items in the index (default)
    --delta     Only document items modified since last run

Output:
    .cb/modules/<alias>/documentation/
        ├── module.json
        ├── entities/
        │   └── <alias>_<EntityName>.json
        ├── attributes/
        │   └── <alias>_<EntityName>_<attrName>.json
        └── attribute_values/
            └── <alias>_<EntityName>_<attrName>_<value>.json

This script provides helper functions for Claude agents to:
1. Load the index and understand what needs documenting
2. Save generated documentation in the correct format
3. Track progress and ensure completeness
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field

# Determine paths
SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_DIR = SCRIPT_DIR.parent
PROJECT_ROOT = SKILL_DIR.parent.parent.parent
CB_DIR = PROJECT_ROOT / ".cb"
MODULES_DIR = CB_DIR / "modules"
BACKEND_SRC = PROJECT_ROOT / "backend" / "src" / "main" / "java" / "com" / "mvs" / "backend"


@dataclass
class DocumentationProgress:
    """Track documentation progress."""
    module_documented: bool = False
    entities_total: int = 0
    entities_documented: int = 0
    attributes_total: int = 0
    attributes_documented: int = 0
    enum_values_total: int = 0
    enum_values_documented: int = 0

    @property
    def is_complete(self) -> bool:
        return (
            self.module_documented and
            self.entities_documented >= self.entities_total and
            self.attributes_documented >= self.attributes_total and
            self.enum_values_documented >= self.enum_values_total
        )

    @property
    def completion_percent(self) -> float:
        total = 1 + self.entities_total + self.attributes_total + self.enum_values_total
        done = (1 if self.module_documented else 0) + self.entities_documented + self.attributes_documented + self.enum_values_documented
        return (done / total * 100) if total > 0 else 0


def load_index(module_alias: str) -> Optional[Dict]:
    """Load the index file for a module."""
    index_file = MODULES_DIR / module_alias / f"{module_alias}_index.json"
    if not index_file.exists():
        print(f"Error: Index file not found: {index_file}")
        print(f"Run: python generate_index.py --module {module_alias}")
        return None

    with open(index_file, 'r', encoding='utf-8') as f:
        return json.load(f)


def load_state(module_alias: str) -> Optional[Dict]:
    """Load the state file for a module."""
    state_file = MODULES_DIR / module_alias / f"{module_alias}_state.json"
    if state_file.exists():
        with open(state_file, 'r', encoding='utf-8') as f:
            return json.load(f)
    return None


def ensure_doc_directories(module_alias: str):
    """Create documentation directory structure."""
    doc_dir = MODULES_DIR / module_alias / "documentation"
    (doc_dir / "entities").mkdir(parents=True, exist_ok=True)
    (doc_dir / "attributes").mkdir(parents=True, exist_ok=True)
    (doc_dir / "attribute_values").mkdir(parents=True, exist_ok=True)
    return doc_dir


def save_module_documentation(module_alias: str, documentation: Dict) -> Path:
    """Save module-level documentation."""
    doc_dir = ensure_doc_directories(module_alias)
    file_path = doc_dir / "module.json"

    doc_content = {
        "metadata": {
            "docType": "module",
            "moduleAlias": module_alias,
            "generatedAt": datetime.now().isoformat(),
            "generatedBy": "Claude Technical Documenter"
        },
        "data": documentation
    }

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(doc_content, f, indent=2, ensure_ascii=False)

    return file_path


def save_entity_documentation(module_alias: str, entity_alias: str, documentation: Dict) -> Path:
    """Save entity-level documentation."""
    doc_dir = ensure_doc_directories(module_alias)
    safe_name = entity_alias.replace(".", "_")
    file_path = doc_dir / "entities" / f"{safe_name}.json"

    doc_content = {
        "metadata": {
            "docType": "entity",
            "entityAlias": entity_alias,
            "generatedAt": datetime.now().isoformat(),
            "generatedBy": "Claude Technical Documenter"
        },
        "data": documentation
    }

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(doc_content, f, indent=2, ensure_ascii=False)

    return file_path


def save_attribute_documentation(module_alias: str, entity_alias: str, attribute_name: str, documentation: Dict) -> Path:
    """Save attribute-level documentation."""
    doc_dir = ensure_doc_directories(module_alias)
    safe_entity = entity_alias.replace(".", "_")
    file_path = doc_dir / "attributes" / f"{safe_entity}_{attribute_name}.json"

    doc_content = {
        "metadata": {
            "docType": "attribute",
            "entityAlias": entity_alias,
            "attributeName": attribute_name,
            "generatedAt": datetime.now().isoformat(),
            "generatedBy": "Claude Technical Documenter"
        },
        "data": documentation
    }

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(doc_content, f, indent=2, ensure_ascii=False)

    return file_path


def save_attribute_value_documentation(module_alias: str, entity_alias: str, attribute_name: str, value_name: str, documentation: Dict) -> Path:
    """Save attribute value (enum) documentation."""
    doc_dir = ensure_doc_directories(module_alias)
    safe_entity = entity_alias.replace(".", "_")
    file_path = doc_dir / "attribute_values" / f"{safe_entity}_{attribute_name}_{value_name}.json"

    doc_content = {
        "metadata": {
            "docType": "attributeValue",
            "entityAlias": entity_alias,
            "attributeName": attribute_name,
            "valueName": value_name,
            "generatedAt": datetime.now().isoformat(),
            "generatedBy": "Claude Technical Documenter"
        },
        "data": documentation
    }

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(doc_content, f, indent=2, ensure_ascii=False)

    return file_path


def get_documentation_progress(module_alias: str, index: Dict) -> DocumentationProgress:
    """Check current documentation progress against index."""
    progress = DocumentationProgress()
    doc_dir = MODULES_DIR / module_alias / "documentation"

    # Check module documentation
    progress.module_documented = (doc_dir / "module.json").exists()

    # Count entities
    for entity in index.get("entities", []):
        progress.entities_total += 1
        safe_name = entity["alias"].replace(".", "_")
        if (doc_dir / "entities" / f"{safe_name}.json").exists():
            progress.entities_documented += 1

        # Count attributes
        for attr in entity.get("attributes", []):
            progress.attributes_total += 1
            if (doc_dir / "attributes" / f"{safe_name}_{attr['name']}.json").exists():
                progress.attributes_documented += 1

            # Count enum values
            for value in attr.get("enumValues", []):
                progress.enum_values_total += 1
                if (doc_dir / "attribute_values" / f"{safe_name}_{attr['name']}_{value}.json").exists():
                    progress.enum_values_documented += 1

    # Also count standalone enums
    for enum in index.get("enums", []):
        for value in enum.get("values", []):
            progress.enum_values_total += 1
            # Enum values are stored with their enum name as attribute name
            enum_name = enum["name"]
            # Find which entity uses this enum (or use module-level)
            if (doc_dir / "attribute_values" / f"{module_alias}_{enum_name}_{value['name']}.json").exists():
                progress.enum_values_documented += 1

    return progress


def get_missing_items(module_alias: str, index: Dict) -> Dict[str, List]:
    """Get list of items that still need documentation."""
    missing = {
        "module": False,
        "entities": [],
        "attributes": [],
        "enum_values": []
    }

    doc_dir = MODULES_DIR / module_alias / "documentation"

    # Check module
    if not (doc_dir / "module.json").exists():
        missing["module"] = True

    # Check entities and their attributes
    for entity in index.get("entities", []):
        safe_name = entity["alias"].replace(".", "_")

        if not (doc_dir / "entities" / f"{safe_name}.json").exists():
            missing["entities"].append(entity)

        for attr in entity.get("attributes", []):
            if not (doc_dir / "attributes" / f"{safe_name}_{attr['name']}.json").exists():
                missing["attributes"].append({
                    "entityAlias": entity["alias"],
                    "attribute": attr
                })

            for value in attr.get("enumValues", []):
                if not (doc_dir / "attribute_values" / f"{safe_name}_{attr['name']}_{value}.json").exists():
                    missing["enum_values"].append({
                        "entityAlias": entity["alias"],
                        "attributeName": attr["name"],
                        "valueName": value
                    })

    return missing


def read_java_source(module_alias: str, relative_path: str) -> Optional[str]:
    """Read a Java source file for documentation context."""
    source_root = BACKEND_SRC / module_alias
    file_path = source_root / relative_path

    if file_path.exists():
        return file_path.read_text(encoding='utf-8')
    return None


def update_state_after_documentation(module_alias: str, progress: DocumentationProgress):
    """Update the state file after documentation generation."""
    state_file = MODULES_DIR / module_alias / f"{module_alias}_state.json"

    state = {}
    if state_file.exists():
        with open(state_file, 'r', encoding='utf-8') as f:
            state = json.load(f)

    state["lastDocumentedAt"] = datetime.now().isoformat()
    state["lastDocumentedBy"] = "Claude Technical Documenter"
    state["documentationProgress"] = {
        "moduleDocumented": progress.module_documented,
        "entitiesTotal": progress.entities_total,
        "entitiesDocumented": progress.entities_documented,
        "attributesTotal": progress.attributes_total,
        "attributesDocumented": progress.attributes_documented,
        "enumValuesTotal": progress.enum_values_total,
        "enumValuesDocumented": progress.enum_values_documented,
        "completionPercent": progress.completion_percent,
        "isComplete": progress.is_complete
    }

    with open(state_file, 'w', encoding='utf-8') as f:
        json.dump(state, f, indent=2, ensure_ascii=False)


def print_documentation_checklist(module_alias: str, index: Dict):
    """Print a checklist of what needs to be documented."""
    print(f"\n{'='*60}")
    print(f"Documentation Checklist for Module: {module_alias}")
    print(f"{'='*60}")

    progress = get_documentation_progress(module_alias, index)

    print(f"\nModule: {index.get('moduleName', module_alias)}")
    print(f"  Source: {index.get('sourceRoot', 'N/A')}")
    print(f"  Index generated: {index.get('generatedAt', 'N/A')}")

    print(f"\nProgress: {progress.completion_percent:.1f}% complete")
    print(f"  Module: {'✓' if progress.module_documented else '○'}")
    print(f"  Entities: {progress.entities_documented}/{progress.entities_total}")
    print(f"  Attributes: {progress.attributes_documented}/{progress.attributes_total}")
    print(f"  Enum Values: {progress.enum_values_documented}/{progress.enum_values_total}")

    if progress.is_complete:
        print(f"\n✓ Documentation is COMPLETE!")
    else:
        missing = get_missing_items(module_alias, index)

        if missing["module"]:
            print(f"\n○ Module documentation needed")

        if missing["entities"]:
            print(f"\n○ Entities needing documentation ({len(missing['entities'])}):")
            for entity in missing["entities"][:10]:
                attr_count = len(entity.get("attributes", []))
                print(f"    - {entity['alias']} ({attr_count} attributes)")
            if len(missing["entities"]) > 10:
                print(f"    ... and {len(missing['entities']) - 10} more")

        if missing["attributes"]:
            print(f"\n○ Attributes needing documentation ({len(missing['attributes'])}):")
            for item in missing["attributes"][:10]:
                print(f"    - {item['entityAlias']}.{item['attribute']['name']}")
            if len(missing["attributes"]) > 10:
                print(f"    ... and {len(missing['attributes']) - 10} more")

    print()


def main():
    parser = argparse.ArgumentParser(
        description="Generate CB technical documentation from index",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
This script is designed to be used by Claude Code agents for documentation generation.

Workflow:
1. First run generate_index.py to create the index
2. Then run this script to see what needs documenting
3. Claude agents use the helper functions to save documentation

Example:
    # Check what needs documenting
    python generate_documentation.py --module cr --status

    # Show full checklist
    python generate_documentation.py --module cr --checklist
        """
    )

    parser.add_argument("--module", required=True, help="Module alias to document")
    parser.add_argument("--status", action="store_true", help="Show documentation status")
    parser.add_argument("--checklist", action="store_true", help="Show full documentation checklist")
    parser.add_argument("--delta", action="store_true", help="Only show items modified since last run")
    parser.add_argument("--json", action="store_true", help="Output in JSON format")

    args = parser.parse_args()

    # Load index
    index = load_index(args.module)
    if index is None:
        sys.exit(1)

    if args.status or args.checklist:
        if args.json:
            progress = get_documentation_progress(args.module, index)
            missing = get_missing_items(args.module, index)
            output = {
                "module": args.module,
                "progress": {
                    "moduleDocumented": progress.module_documented,
                    "entitiesTotal": progress.entities_total,
                    "entitiesDocumented": progress.entities_documented,
                    "attributesTotal": progress.attributes_total,
                    "attributesDocumented": progress.attributes_documented,
                    "enumValuesTotal": progress.enum_values_total,
                    "enumValuesDocumented": progress.enum_values_documented,
                    "completionPercent": progress.completion_percent,
                    "isComplete": progress.is_complete
                },
                "missing": missing
            }
            print(json.dumps(output, indent=2))
        else:
            print_documentation_checklist(args.module, index)
    else:
        # Default: show status
        print_documentation_checklist(args.module, index)


if __name__ == "__main__":
    main()
